version: '3'
services:
  db:
    image: "my-mysql"
    ports: 
     - "3306:3306"
    environment: 
     - MYSQL_ROOT_PASSWORD=1234
  node:
    image: "node-app"
    ports: 
     - "3000:3000"
    links:
     - db
